### ISSUE TITLE
Concentration of Economic Activity

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/egypt-economic-monitor#6]
> Can we illustrate the fact that economic activity is concentrated in only about 7% of Egypt’s land? (Perhaps through Nighttime Lights. Would be great if we showed 3 points in time if data allow… say 2000 ; 2011 ; & 2023 and then contrast them with a comparator – say Turkey) For the more frequent macro monitoring, would there be data to look at the issue of rising electricity cuts in recent months? Can we look at Nighttime lights in January 2023, and compare it to the latest data point available?

Since agriculture comprises only ~10% of the Egyptian economy, the team proposes leveraging alternative data sources to understand the geospatial concentration of industry and services, namely: nighttime lights, internet connectivity, industrial air pollution, and commerce-based points of interest.

**Comment by Holly-Transport** [comment]
Final notebook still does not show percent of land with highest level of consistent NTL. Please add.
